name: 'Terraform Plan'
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
defaults:
      run:
        shell: bash

jobs:
  terraform_fmt_check:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        
      - name: 'Terraform Init'
        run: terraform init
      
      - name: 'Terraform Format'
        run: terraform fmt -check